name: Full CI

on: [push, workflow_dispatch]

jobs:
  full-test:
    name: Full Repository Tests
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.19"
      - name: Check formatting
        run: test -z "$(gofmt -s -l $(find . -name '*.go' -type f -print) | tee /dev/stderr)"
      - name: Run full tests
        run: make test
